"""empty message

Revision ID: 196a1c3eac7c
Revises: c7d4bfb142b6
Create Date: 2019-01-23 15:20:52.212240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '196a1c3eac7c'
down_revision = 'c7d4bfb142b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation', 'number0',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation', 'number0',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
