"""empty message

Revision ID: c7d4bfb142b6
Revises: 
Create Date: 2019-01-23 10:31:29.257428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
import src

revision = 'c7d4bfb142b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('middle_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_ts', src.database.models.AwareDateTime(), nullable=True),
    sa.Column('last_modified_ts', src.database.models.AwareDateTime(), nullable=True),
    sa.Column('deleted_ts', src.database.models.AwareDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=300), nullable=False),
    sa.Column('created_ts', src.database.models.AwareDateTime(), nullable=True),
    sa.Column('operator', sa.String(length=1), nullable=False),
    sa.Column('number0', sa.Float(), nullable=False),
    sa.Column('number1', sa.Float(), nullable=True),
    sa.Column('result', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation')
    op.drop_table('user')
    # ### end Alembic commands ###
